/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_call */

#ifndef _Included_JNI_call
#define _Included_JNI_call
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_call
 * Method:    get_auth
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_1call_get_1auth
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
